# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-01 01:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models
import everyvoter_common.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election', '0004_state_demonym'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(choices=[(b'election_date', b'Election Date'), (b'vr_deadline', b'Voter Registration Deadline'), (b'vr_deadline_online', b'Online Voter Registration Deadline'), (b'evip_start_date', b'Early Vote In-Person Start Date'), (b'evip_close_date', b'Early Vote In-Person Close Date'), (b'vbm_application_deadline', b'Vote By Mail Application Deadline'), (b'vbm_return_date', b'Vote By Mail Ballot Return Date')], max_length=50)),
                ('old_date', models.DateField(null=True)),
                ('new_date', models.DateField(null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Election')),
            ],
            options={
                'verbose_name': 'Change',
                'verbose_name_plural': 'Changes',
            },
            bases=(everyvoter_common.utils.models.CacheMixinModel, models.Model),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('elections', models.ManyToManyField(to='election.Election')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'API Response',
                'verbose_name_plural': 'API Responses',
            },
            bases=(everyvoter_common.utils.models.CacheMixinModel, models.Model),
        ),
        migrations.AddField(
            model_name='datechange',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='democracy_consumer.Response'),
        ),
        migrations.AlterUniqueTogether(
            name='datechange',
            unique_together=set([('field', 'response', 'election')]),
        ),
    ]
