# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 16:07
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models
import kennedy_common.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('activity', models.CharField(choices=[(b'send', b'Sent'), (b'bounce', b'Bounce'), (b'complaint', b'Complaint'), (b'open', b'Open'), (b'click', b'Click')], max_length=50, verbose_name=b'Action Type')),
                ('link', models.CharField(default=None, max_length=500, null=True, verbose_name=b'Click URL')),
            ],
            options={
                'verbose_name': 'Email Activity',
                'verbose_name_plural': 'Email Activities',
            },
            bases=(kennedy_common.utils.models.CacheMixinModel, models.Model),
        ),
        migrations.CreateModel(
            name='EmailWrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name=b'Name')),
                ('header', models.TextField(verbose_name=b'Header')),
                ('footer', models.TextField(verbose_name=b'Footer')),
                ('default', models.BooleanField(default=False, verbose_name=b'Default')),
            ],
            options={
                'verbose_name': 'Email Wrapper',
                'verbose_name_plural': 'Email Wrappers',
            },
            bases=(kennedy_common.utils.models.CacheMixinModel, models.Model),
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, unique=True)),
                ('subject', models.CharField(max_length=100, verbose_name=b'Subject Line')),
                ('pre_header', models.CharField(max_length=100, null=True, verbose_name=b'Pre-Header Text')),
                ('from_name', models.CharField(max_length=50, verbose_name=b'From Name')),
                ('from_email', models.EmailField(max_length=254, verbose_name=b'From Email')),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name=b'Stats')),
                ('source', models.CharField(max_length=100, verbose_name=b'Source Code')),
                ('body', models.TextField(verbose_name=b'Email Body')),
                ('count', models.IntegerField(default=0, verbose_name=b'Recipients')),
            ],
            options={
                'verbose_name': 'Mailing',
                'verbose_name_plural': 'Mailings',
            },
            bases=(kennedy_common.utils.models.CacheMixinModel, models.Model),
        ),
        migrations.CreateModel(
            name='Unsubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('origin', models.CharField(choices=[(b'user', b'Manual'), (b'bounce', b'Bounce'), (b'complaint', b'Complaint')], max_length=50)),
            ],
            options={
                'verbose_name': 'Unsubscribe',
                'verbose_name_plural': 'Unsubscribes',
            },
            bases=(kennedy_common.utils.models.CacheMixinModel, models.Model),
        ),
    ]
