# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('election', '0003_organization_election'),
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailactivity',
            name='mailing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailer.Mailing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailactivity',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailwrapper',
            name='organization',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='branding.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='organization_election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='election.OrganizationElection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unsubscribe',
            name='mailing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailer.Mailing'),
        ),
        migrations.AddField(
            model_name='unsubscribe',
            name='organization',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='branding.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unsubscribe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
