# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 20:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='organization_election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='election.OrganizationElection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unsubscribe',
            name='mailing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailer.Mailing'),
        ),
        migrations.AddField(
            model_name='unsubscribe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
