# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_foreign_relationships'),
        ('mailer', '0002_foreign_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='blocks',
            field=models.ManyToManyField(through='blocks.MailingBlocks', to='blocks.Block', blank=True),
        ),
        migrations.AddField(
            model_name='mailingtemplate',
            name='blocks',
            field=models.ManyToManyField(through='blocks.TemplateBlocks', to='blocks.Block', blank=True),
        ),
    ]
