# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 03:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_foreign_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsubscribe',
            name='global_unsub',
            field=models.BooleanField(db_index=True, default=False, verbose_name=b'Applies Globally'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unsubscribe',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Reason'),
        ),
        migrations.AlterField(
            model_name='unsubscribe',
            name='organization',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='branding.Organization'),
        ),
        migrations.AddField(
            model_name='emailactivity',
            name='message_id',
            field=models.CharField(default='', max_length=100, verbose_name=b'Message ID from ESP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailactivity',
            name='activity',
            field=models.CharField(choices=[(b'send', b'Sent'), (b'bounce', b'Bounce'), (b'soft_bounce', b'Soft Bounce'), (b'complaint', b'Complaint'), (b'open', b'Open'), (b'click', b'Click')], max_length=50, verbose_name=b'Action Type'),
        ),
        migrations.AlterField(
            model_name='emailactivity',
            name='mailing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailer.Mailing'),
        ),
        migrations.AlterField(
            model_name='emailactivity',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
