# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_email_blocks'),
        ('mailer', '0002_foreign_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='blocks',
            field=models.ManyToManyField(blank=True, through='blocks.EmailBlocks', to='blocks.Block'),
        ),
    ]
