# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_sending_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingtemplate',
            name='active',
            field=models.BooleanField(db_index=True, default=True, editable=False, verbose_name=b'Active Template'),
        ),
        migrations.AlterField(
            model_name='emailactivity',
            name='mailing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailer.Mailing'),
        ),
        migrations.AlterField(
            model_name='emailactivity',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailer.MailingTemplate'),
        ),
    ]
