# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_sending_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailTags',
            new_name='EmailCategory',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='tags',
            new_name='categories',
        ),
    ]
