# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 05:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import everyvoter_common.utils.models
import rendering.validators


def create_default_sending_address(apps, schema_editor):
    """Assign a default primary domain for each org"""
    SendingAddress = apps.get_model('mailer', 'SendingAddress')
    SendingAddress.objects.get_or_create(
        address=settings.DEFAULT_FROM_EMAIL, id=1)


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
        ('mailer', '0004_email_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('address', models.EmailField(max_length=254, verbose_name=b'Email Address')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_addresses', to='branding.Organization', null=True, blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(everyvoter_common.utils.models.CacheMixinModel, models.Model),
        ),
        migrations.RunPython(create_default_sending_address, lambda x,y: None)
    ]
