# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0006_fk_email_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='sent',
            field=models.IntegerField(default=0, verbose_name=b'Total Sent'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[(b'pending', b'Pending'), (b'queued', b'Queued'), (b'sending', b'Sending'), (b'sent', b'Sent'), (b'terminated', b'Terminated'), (b'failed', b'Failed')], default=b'pending', max_length=50, verbose_name=b'Mailing Status'),
        ),
    ]
