# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-12 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_mailing_send_stats_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailactivity',
            index=models.Index(fields=[b'email', b'activity'], name=b'email_specific_activity_idx'),
        ),
    ]
