# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0010_send_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingtemplate',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name=b'Deleted'),
        ),
    ]
