# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kennedy_common.utils.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lookups',
            field=models.ManyToManyField(to='location.GeoLookup'),
        ),
        migrations.AddField(
            model_name='location',
            name='districts',
            field=models.ManyToManyField(to='election.LegislativeDistrict'),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.ForeignKey(default='WI', db_index=True, on_delete=django.db.models.deletion.CASCADE, to='election.State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userlocation',
            unique_together=set([('user', 'is_active')]),
        ),
    ]
