# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='districts',
            field=models.ManyToManyField(to='election.LegislativeDistrict'),
        ),
        migrations.AddField(
            model_name='location',
            name='lookups',
            field=models.ManyToManyField(to='location.GeoLookup'),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='election.State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlocation',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
