# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_foreign_relationships'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlocation',
            unique_together=set([]),
        ),
    ]
