# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_foreign_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolookup',
            name='lookup',
            field=models.CharField(db_index=True, help_text=b'Address provided by user', max_length=255, verbose_name=b'Lookup'),
        ),
    ]
