# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_remove_active_db_unique'),
        ('accounts', '0004_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='is_active',
        ),
    ]
