# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
        ('election', '0003_organization_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationelection',
            name='email_wrapper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailer.EmailWrapper'),
            preserve_default=False,
        ),
    ]
