# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 05:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_load_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='polls_close',
        ),
        migrations.RemoveField(
            model_name='election',
            name='polls_notes',
        ),
        migrations.RemoveField(
            model_name='election',
            name='polls_open',
        ),
        migrations.AddField(
            model_name='election',
            name='ballot_return_date',
            field=models.DateField(default=datetime.datetime.now().date(), help_text=b'The date by which voters must return their mailed ballots', verbose_name=b'Vote By Mail Ballot Return Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='election',
            name='evip_close_date',
            field=models.DateField(blank=True, help_text=b'The date that early voting in person ends in the state', null=True, verbose_name=b'Early Vote In-Person Close Date'),
        ),
        migrations.AddField(
            model_name='election',
            name='evip_start_date',
            field=models.DateField(blank=True, help_text=b'The date in which early voting in person begins in the state', null=True, verbose_name=b'Early Vote In-Person Start Date'),
        ),
        migrations.AddField(
            model_name='election',
            name='online_vr_deadline',
            field=models.DateField(blank=True, help_text=b'The explicit deadline by which voters in the state must register to vote online in order to vote', null=True, verbose_name=b'Online Voter Registration Deadline'),
        ),
        migrations.AddField(
            model_name='election',
            name='vbm_application_deadline',
            field=models.DateField(default=datetime.datetime.now().date(), help_text=b'the date by which voters must return their applications applying to vote by mail', verbose_name=b'Vote By Mail Application Deadline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='election',
            name='vr_deadline',
            field=models.DateField(default=datetime.datetime.now().date(), help_text=b'The deadline by which voters in the state must register to vote', verbose_name=b'Voter Registration Deadline'),
            preserve_default=False,
        ),
    ]
