# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 16:01
from __future__ import unicode_literals

from django.db import migrations, models


def update_north_dakota(apps, schema_editor):
    """North Dakota doesn't register voters"""
    State = apps.get_model('election', 'State')
    State.objects.filter(code='ND').update(has_vr=False)


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_fill_out_election_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='has_vr',
            field=models.BooleanField(default=True, help_text=b"Whether the state registers voters (North Dakota doesn't)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='vr_deadline',
            field=models.DateField(blank=True, help_text=b'The deadline by which voters in the state must register to vote', null=True, verbose_name=b'Voter Registration Deadline'),
        ),
        migrations.RunPython(update_north_dakota, lambda x,y: None)
    ]
