# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models
import kennedy_common.utils.models
import rendering.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name=b'Block Name')),
                ('code', models.TextField(validators=[rendering.validators.validate_template], verbose_name=b'HTML Code')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='branding.Organization')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
            },
            bases=(kennedy_common.utils.models.CacheMixinModel, models.Model),
        ),
        migrations.CreateModel(
            name='BlockTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name=b'Blog Tag Name')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='branding.Organization')),
            ],
            options={
                'verbose_name': 'Block Tag',
                'verbose_name_plural': 'Block Tags',
            },
            bases=(kennedy_common.utils.models.CacheMixinModel, models.Model),
        ),
        migrations.CreateModel(
            name='MailingBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.Block')),
            ],
            options={
                'verbose_name': 'Mailing Blocks',
                'verbose_name_plural': 'Mailing Blocks',
            },
            bases=(kennedy_common.utils.models.CacheMixinModel, models.Model),
        ),
        migrations.CreateModel(
            name='TemplateBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.Block')),
            ],
            options={
                'verbose_name': 'Template Blocks',
                'verbose_name_plural': 'Template Blocks',
            },
            bases=(kennedy_common.utils.models.CacheMixinModel, models.Model),
        ),
        migrations.AddField(
            model_name='block',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blocks.BlockTag'),
        ),
    ]
