# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_email_blocks'),
        ('mailer', '0009_remove_email_blocks_intermediate')
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailblocks',
            name='block',
        ),
        migrations.RemoveField(
            model_name='emailblocks',
            name='email',
        ),
        migrations.DeleteModel(
            name='EmailBlocks',
        ),
    ]
