# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_remove_email_blocks_intermediate'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name=b'Deleted'),
        ),
    ]
