# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import kennedy_common.utils.models


def create_default_org(apps, schema_editor):
    """Create the first org"""
    Domain = apps.get_model('branding', 'Domain')
    Organization = apps.get_model('branding', 'Organization')

    org = Organization.objects.create(name='Default', homepage='http://localhost', platform_name='Voting System')
    Domain.objects.create(hostname='localhost', organization=org)
    Domain.objects.create(hostname='testserver', organization=org)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('hostname', models.CharField(max_length=100, unique=True, verbose_name=b'Hostname')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
            bases=(kennedy_common.utils.models.CacheMixinModel, models.Model),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name=b'Name')),
                ('platform_name', models.CharField(max_length=50, verbose_name=b'Platform Name')),
                ('homepage', models.URLField(verbose_name=b'Homepage')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
            bases=(kennedy_common.utils.models.CacheMixinModel, models.Model),
        ),
        migrations.AddField(
            model_name='domain',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='branding.Organization'),
        ),
        migrations.RunPython(create_default_org, lambda x,y: None)
    ]
