# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import kennedy_common.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('hostname', models.CharField(max_length=100, unique=True, verbose_name=b'Hostname')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
            bases=(kennedy_common.utils.models.CacheMixinModel, models.Model),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name=b'Name')),
                ('homepage', models.URLField(verbose_name=b'Homepage')),
                ('platform_name', models.CharField(max_length=50, verbose_name=b'Platform Name')),
                ('privacy_url', models.URLField(verbose_name=b'Privacy Policy URL')),
                ('terms_url', models.URLField(verbose_name=b'Terms of Service URL')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
            bases=(kennedy_common.utils.models.CacheMixinModel, models.Model),
        ),
    ]
