# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branding.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='elections',
            field=models.ManyToManyField(through='election.OrganizationElection', to='election.Election'),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_domain',
            field=models.ForeignKey(default=None, help_text=b'Domain to attach all links to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_domain', to='branding.Domain', verbose_name=b'Primary Domain'),
        ),
    ]
