# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='elections',
            field=models.ManyToManyField(through='election.OrganizationElection', to='election.Election'),
        ),
    ]
