# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_organization_election'),
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='elections',
            field=models.ManyToManyField(through='election.OrganizationElection', to='election.Election'),
        ),
    ]
