# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
        ('branding', '0002_foreign_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='from_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='default_organizations', to='mailer.SendingAddress', verbose_name=b'Sending Address'),
        ),
    ]
