# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_sending_address'),
        ('branding', '0003_create_initial_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='from_address',
            field=models.ForeignKey(default=1, on_delete=models.SET_DEFAULT, related_name='default_organizations', to='mailer.SendingAddress'),
            preserve_default=False,
        ),
    ]
