# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0003_organization_primary_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='privacy_url',
            field=models.URLField(default='', verbose_name=b'Privacy Policy URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='terms_url',
            field=models.URLField(default='', verbose_name=b'Terms of Service URL'),
            preserve_default=False,
        ),
    ]
