# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-12 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0004_create_initial_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email_active',
            field=models.BooleanField(default=False, verbose_name=b'Bulk email enabled'),
        ),
    ]
