# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-18 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0006_organization_main_unsubscribe_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='disable_vr_eday',
            field=models.BooleanField(default=True, help_text=b"In some states, you're able to register to vote on Election Day. These automatic reminders may overlap with other Election Day reminders your organization has scheduled. Check this box to disable Voter Registration reminders for all states where it's possible to register on Election Day.", verbose_name=b'Disable Election Day Voter Registration Reminders'),
        ),
        migrations.AddField(
            model_name='organization',
            name='disable_vr_sameday',
            field=models.BooleanField(default=True, help_text=b"In some states, you're able to register to vote on the same day as you vote (but not necessarily on Election Day.) These automatic reminders may overlap with other Election Day reminders your organization has scheduled. Check this box to disable Voter Registration reminders for all states where it's possible to register the same day you vote (for voting before Election Day)", verbose_name=b'Disable Same Day Voter Registration Reminders'),
        ),
    ]
