# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
        ('election', '0001_initial'),
        ('targeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='blocks',
            field=models.ManyToManyField(blank=True, to='blocks.Block'),
        ),
        migrations.AddField(
            model_name='target',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='election.LegislativeDistrict'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='election.Election'),
            preserve_default=False,
        ),
    ]
