# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('branding', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(through='location.UserLocation', to='location.Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(db_index=True, default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='branding.Organization'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('email', 'organization')]),
        ),
    ]
