# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(related_name='userlocations_set', through='location.UserLocation', to='location.Location'),
        ),
    ]
