# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 02:09
from __future__ import unicode_literals

from django.db import migrations
from django.db import models
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_foreign_relationships'),
    ]

    operations = [
        # In order to migrate from a `UUIDField` to a `SmallUUIDField` we have
        # to remove the `unique` index (temporarially) on the username field.
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, unique=True, verbose_name=b'Username'),
        ),

        migrations.AddField(
            model_name='user',
            name='unsubscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=[b'organization', b'is_active', b'unsubscribed'], name=b'org_active_unsub_idx'),
        ),
    ]
