# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def attach_location(apps, schema_editor):
    UserLocation = apps.get_model('location', 'UserLocation')
    User = apps.get_model('accounts', 'User')

    for user in User.objects.all():
        user.location = UserLocation.objects.get(
            user=user, is_active=True).location
        user.save()


def undo_location(apps, schema_editor):
    UserLocation = apps.get_model('location', 'UserLocation')
    User = apps.get_model('accounts', 'User')

    for user in User.objects.all():
        ul = UserLocation(user=user, location=user.location)
        ul.save()


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_foreign_relationships'),
        ('accounts', '0003_smalluuid_unsubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userlocations_set', to='location.Location'),
        ),
        migrations.RunPython(attach_location, undo_location),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlocations_set', to='location.Location'),
        ),
    ]
