# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_foreign_relationships'),
        ('geodataset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='election.LegislativeDistrict'),
            preserve_default=False,
        ),
    ]
