# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 16:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import everyvoter_common.utils.models
import everyvoter_common.utils.storages
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Import Record',
                'verbose_name_plural': 'Import Records',
            },
        ),
        migrations.CreateModel(
            name='ImportRecordStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(b'success', b'Succeeded'), (b'failed', b'Failed')], max_length=50)),
                ('note', models.TextField(null=True)),
                ('error_type', models.CharField(max_length=100, null=True)),
                ('import_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_import.ImportRecord')),
            ],
            options={
                'verbose_name': 'Import Record Status',
                'verbose_name_plural': 'Import Record Statuses',
            },
            bases=(everyvoter_common.utils.models.CacheMixinModel, models.Model),
        ),
        migrations.CreateModel(
            name='UserImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name=b'Import Name')),
                ('total_succeeded', models.IntegerField(default=0, editable=False, verbose_name=b'Total Users Created')),
                ('total_failed', models.IntegerField(default=0, editable=False, verbose_name=b'Total Failures')),
                ('ingested', models.IntegerField(default=0, editable=False, verbose_name=b'Total Ingested')),
                ('status', models.CharField(choices=[(b'pending', b'Pending'), (b'failed', b'Failed'), (b'ingesting', b'Ingesting'), (b'creating', b'Creating Users'), (b'finished', b'Finished')], max_length=50, verbose_name=b'Status')),
                ('file', models.FileField(null=True, storage=everyvoter_common.utils.storages.HighValueStorage(), upload_to=b'user_imports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=[b'csv'])], verbose_name=b'Source File')),
                ('default', models.BooleanField(default=False, editable=False, verbose_name=b'Default API Import')),
                ('note', models.TextField(default=False, null=True)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='branding.Organization')),
            ],
            options={
                'ordering': ['-modified_at'],
                'verbose_name': 'User Import',
                'verbose_name_plural': 'User Imports',
            },
            bases=(everyvoter_common.utils.models.CacheMixinModel, models.Model),
        ),
        migrations.AddField(
            model_name='importrecordstatus',
            name='user_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_import.UserImport'),
        ),
        migrations.AddField(
            model_name='importrecord',
            name='user_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_import.UserImport'),
        ),
    ]
