# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrecordstatus',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importrecordstatus',
            name='user_import',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_import.UserImport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userimport',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
