# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 17:46
from __future__ import unicode_literals

from django.db import migrations, models


def add_default_records(apps, schema_editor):
    """Add an 'Default Import' record (used in API calls)"""
    Organization = apps.get_model('branding', 'Organization')
    UserImport = apps.get_model('user_import', 'userImport')

    for organization in Organization.objects.all():
        try:
            UserImport.objects.get(default=True, organization=organization)
        except UserImport.DoesNotExist:
            new_user_import = UserImport()
            new_user_import.name = '{} Default/Generic Import'.format(
                organization.name)
            new_user_import.count = 0
            new_user_import.organization = organization
            new_user_import.default = True
            new_user_import.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user_import', '0002_foreign_relationships'),
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimport',
            name='count',
            field=models.IntegerField(default=0, editable=False, verbose_name=b'Total Records'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='userimport',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name=b'Import Name'),
            preserve_default=False,
        ),
        migrations.RunPython(add_default_records, lambda x, y: None)
    ]
