# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-08 19:23
from __future__ import unicode_literals
import uuid

from django.db import migrations
import django_smalluuid.models


def set_uuids(apps, schema_editor):
    """Load states"""
    UserImport = apps.get_model('user_import', 'UserImport')

    for user_import in UserImport.objects.all():
        user_import.uuid = uuid.uuid4()
        user_import.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user_import', '0002_foreign_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimport',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=None, editable=False, null=True),
        ),
        migrations.RunPython(set_uuids, lambda x, y: None),
        migrations.AlterField(
            model_name='userimport',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, unique=True),
        ),
    ]
