# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-07 20:52
from __future__ import unicode_literals

from django.db import migrations
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_import', '0002_foreign_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimport',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, unique=True),
        ),
    ]
