# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 00:52
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import kennedy_common.utils.storages


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_import', '0003_add_defaultrecords_name_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimport',
            options={'ordering': ['-modified_at'], 'verbose_name': 'User Import', 'verbose_name_plural': 'User Imports'},
        ),
        migrations.RemoveField(
            model_name='userimport',
            name='count',
        ),
        migrations.AddField(
            model_name='importrecordstatus',
            name='error_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='importrecordstatus',
            name='user_import',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user_import.UserImport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userimport',
            name='ingested',
            field=models.IntegerField(default=0, editable=False, verbose_name=b'Total Ingested'),
        ),
        migrations.AddField(
            model_name='userimport',
            name='note',
            field=models.TextField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='userimport',
            name='status',
            field=models.CharField(choices=[(b'pending', b'Pending'), (b'failed', b'Failed'), (b'ingesting', b'Ingesting'), (b'creating', b'Creating Users'), (b'finished', b'Finished')], default='finished', max_length=50, verbose_name=b'Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userimport',
            name='total_failed',
            field=models.IntegerField(default=0, editable=False, verbose_name=b'Total Failures'),
        ),
        migrations.AddField(
            model_name='userimport',
            name='total_succeeded',
            field=models.IntegerField(default=0, editable=False, verbose_name=b'Total Users Created'),
        ),
        migrations.AddField(
            model_name='userimport',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userimport',
            name='file',
            field=models.FileField(null=True, storage=kennedy_common.utils.storages.HighValueStorage(), upload_to=b'user_imports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=[b'csv'])], verbose_name=b'Source File'),
        ),
    ]
