# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 16:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branding', '0001_initial'),
        ('import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrecord',
            name='user_import',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='import.UserImport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importrecordstatus',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userimport',
            name='organization',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='branding.Organization'),
            preserve_default=False,
        ),
    ]
