"""OCD ID(s) that map to individual Geocod.io Responses"""


GEOCODIO_OCDIDS_SENATE = {
    'AK': {
        'A': ['ocd-division/country:us/state:ak/sldu:a'],
        'B': ['ocd-division/country:us/state:ak/sldu:b'],
        'C': ['ocd-division/country:us/state:ak/sldu:c'],
        'D': ['ocd-division/country:us/state:ak/sldu:d'],
        'E': ['ocd-division/country:us/state:ak/sldu:e'],
        'F': ['ocd-division/country:us/state:ak/sldu:f'],
        'G': ['ocd-division/country:us/state:ak/sldu:g'],
        'H': ['ocd-division/country:us/state:ak/sldu:h'],
        'I': ['ocd-division/country:us/state:ak/sldu:i'],
        'J': ['ocd-division/country:us/state:ak/sldu:j'],
        'K': ['ocd-division/country:us/state:ak/sldu:k'],
        'L': ['ocd-division/country:us/state:ak/sldu:l'],
        'M': ['ocd-division/country:us/state:ak/sldu:m'],
        'N': ['ocd-division/country:us/state:ak/sldu:n'],
        'O': ['ocd-division/country:us/state:ak/sldu:o'],
        'P': ['ocd-division/country:us/state:ak/sldu:p'],
        'Q': ['ocd-division/country:us/state:ak/sldu:q'],
        'R': ['ocd-division/country:us/state:ak/sldu:r'],
        'S': ['ocd-division/country:us/state:ak/sldu:s'],
        'T': ['ocd-division/country:us/state:ak/sldu:t']
    },
    'DC': {
        '1': ['ocd-division/country:us/district:dc/ward:1'],
        '2': ['ocd-division/country:us/district:dc/ward:2'],
        '3': ['ocd-division/country:us/district:dc/ward:3'],
        '4': ['ocd-division/country:us/district:dc/ward:4'],
        '5': ['ocd-division/country:us/district:dc/ward:5'],
        '6': ['ocd-division/country:us/district:dc/ward:6'],
        '7': ['ocd-division/country:us/district:dc/ward:7'],
        '8': ['ocd-division/country:us/district:dc/ward:8']
    },
    'MA': {
        '1': ['ocd-division/country:us/state:ma/sldu:1st_suffolk'],
        '2': ['ocd-division/country:us/state:ma/sldu:2nd_suffolk'],
        '3': ['ocd-division/country:us/state:ma/sldu:hampden'],
        '4': ['ocd-division/country:us/state:ma/sldu:berkshire_hampshire_franklin_and_hampden'],
        '5': ['ocd-division/country:us/state:ma/sldu:2nd_hampden_and_hampshire'],
        '6': ['ocd-division/country:us/state:ma/sldu:hampshire_franklin_and_worcester'],
        '7': ['ocd-division/country:us/state:ma/sldu:1st_hampden_and_hampshire'],
        '8': ['ocd-division/country:us/state:ma/sldu:worcester_hampden_hampshire_and_middlesex'],
        '9': ['ocd-division/country:us/state:ma/sldu:worcester_and_middlesex'],
        '10': ['ocd-division/country:us/state:ma/sldu:1st_worcester'],
        '11': ['ocd-division/country:us/state:ma/sldu:2nd_worcester'],
        '12': ['ocd-division/country:us/state:ma/sldu:worcester_and_norfolk'],
        '13': ['ocd-division/country:us/state:ma/sldu:1st_middlesex'],
        '14': ['ocd-division/country:us/state:ma/sldu:middlesex_and_worcester'],
        '15': ['ocd-division/country:us/state:ma/sldu:2nd_middlesex_and_norfolk'],
        '16': ['ocd-division/country:us/state:ma/sldu:3rd_middlesex'],
        '17': ['ocd-division/country:us/state:ma/sldu:norfolk_bristol_and_middlesex'],
        '18': ['ocd-division/country:us/state:ma/sldu:2nd_essex_and_middlesex'],
        '19': ['ocd-division/country:us/state:ma/sldu:1st_essex'],
        '20': ['ocd-division/country:us/state:ma/sldu:1st_essex_and_middlesex'],
        '21': ['ocd-division/country:us/state:ma/sldu:2nd_essex'],
        '22': ['ocd-division/country:us/state:ma/sldu:3rd_essex'],
        '23': ['ocd-division/country:us/state:ma/sldu:5th_middlesex'],
        '24': ['ocd-division/country:us/state:ma/sldu:4th_middlesex'],
        '25': ['ocd-division/country:us/state:ma/sldu:2nd_middlesex'],
        '26': ['ocd-division/country:us/state:ma/sldu:middlesex_and_suffolk'],
        '27': ['ocd-division/country:us/state:ma/sldu:1st_suffolk_and_middlesex'],
        '28': ['ocd-division/country:us/state:ma/sldu:2nd_suffolk_and_middlesex'],
        '29': ['ocd-division/country:us/state:ma/sldu:1st_middlesex_and_norfolk'],
        '30': ['ocd-division/country:us/state:ma/sldu:norfolk_and_suffolk'],
        '31': ['ocd-division/country:us/state:ma/sldu:bristol_and_norfolk'],
        '32': ['ocd-division/country:us/state:ma/sldu:norfolk_bristol_and_plymouth'],
        '33': ['ocd-division/country:us/state:ma/sldu:norfolk_and_plymouth'],
        '34': ['ocd-division/country:us/state:ma/sldu:plymouth_and_norfolk'],
        '35': ['ocd-division/country:us/state:ma/sldu:2nd_plymouth_and_bristol'],
        '36': ['ocd-division/country:us/state:ma/sldu:1st_plymouth_and_bristol'],
        '37': ['ocd-division/country:us/state:ma/sldu:1st_bristol_and_plymouth'],
        '38': ['ocd-division/country:us/state:ma/sldu:2nd_bristol_and_plymouth'],
        '39': ['ocd-division/country:us/state:ma/sldu:plymouth_and_barnstable'],
        '40': ['ocd-division/country:us/state:ma/sldu:cape_and_islands']
    },
    'VT': {
        'ADD': ['ocd-division/country:us/state:vt/sldu:addison'],
        'BEN': ['ocd-division/country:us/state:vt/sldu:bennington'],
        'CAL': ['ocd-division/country:us/state:vt/sldu:caledonia'],
        'CGI': ['ocd-division/country:us/state:vt/sldu:grand_isle-chittenden'],
        'CHI': ['ocd-division/country:us/state:vt/sldu:chittenden'],
        'E-O': ['ocd-division/country:us/state:vt/sldu:essex-orleans'],
        'FRA': ['ocd-division/country:us/state:vt/sldu:franklin'],
        'LAM': ['ocd-division/country:us/state:vt/sldu:lamoille'],
        'ORA': ['ocd-division/country:us/state:vt/sldu:orange'],
        'RUT': ['ocd-division/country:us/state:vt/sldu:rutland'],
        'WAS': ['ocd-division/country:us/state:vt/sldu:washington'],
        'WDM': ['ocd-division/country:us/state:vt/sldu:windham'],
        'WSR': ['ocd-division/country:us/state:vt/sldu:windsor']
    }
}


GEOCODIO_OCDIDS_HOUSE = {
    'MA': {
        '60': ['ocd-division/country:us/state:ma/sldl:1st_barnstable'],
        '61': ['ocd-division/country:us/state:ma/sldl:2nd_barnstable'],
        '62': ['ocd-division/country:us/state:ma/sldl:3rd_barnstable'],
        '63': ['ocd-division/country:us/state:ma/sldl:4th_barnstable'],
        '64': ['ocd-division/country:us/state:ma/sldl:barnstable_dukes_and_nantucket'],
        '65': ['ocd-division/country:us/state:ma/sldl:1st_berkshire'],
        '66': ['ocd-division/country:us/state:ma/sldl:2nd_berkshire'],
        '67': ['ocd-division/country:us/state:ma/sldl:3rd_berkshire'],
        '68': ['ocd-division/country:us/state:ma/sldl:4th_berkshire'],
        '69': ['ocd-division/country:us/state:ma/sldl:1st_bristol'],
        '70': ['ocd-division/country:us/state:ma/sldl:2nd_bristol'],
        '71': ['ocd-division/country:us/state:ma/sldl:3rd_bristol'],
        '72': ['ocd-division/country:us/state:ma/sldl:4th_bristol'],
        '73': ['ocd-division/country:us/state:ma/sldl:5th_bristol'],
        '74': ['ocd-division/country:us/state:ma/sldl:6th_bristol'],
        '75': ['ocd-division/country:us/state:ma/sldl:7th_bristol'],
        '76': ['ocd-division/country:us/state:ma/sldl:8th_bristol'],
        '77': ['ocd-division/country:us/state:ma/sldl:9th_bristol'],
        '78': ['ocd-division/country:us/state:ma/sldl:10th_bristol'],
        '79': ['ocd-division/country:us/state:ma/sldl:11th_bristol'],
        '80': ['ocd-division/country:us/state:ma/sldl:12th_bristol'],
        '81': ['ocd-division/country:us/state:ma/sldl:13th_bristol'],
        '82': ['ocd-division/country:us/state:ma/sldl:14th_bristol'],
        '83': ['ocd-division/country:us/state:ma/sldl:1st_essex'],
        '84': ['ocd-division/country:us/state:ma/sldl:2nd_essex'],
        '85': ['ocd-division/country:us/state:ma/sldl:3rd_essex'],
        '86': ['ocd-division/country:us/state:ma/sldl:4th_essex'],
        '87': ['ocd-division/country:us/state:ma/sldl:5th_essex'],
        '88': ['ocd-division/country:us/state:ma/sldl:6th_essex'],
        '89': ['ocd-division/country:us/state:ma/sldl:7th_essex'],
        '90': ['ocd-division/country:us/state:ma/sldl:8th_essex'],
        '91': ['ocd-division/country:us/state:ma/sldl:9th_essex'],
        '92': ['ocd-division/country:us/state:ma/sldl:10th_essex'],
        '93': ['ocd-division/country:us/state:ma/sldl:11th_essex'],
        '94': ['ocd-division/country:us/state:ma/sldl:12th_essex'],
        '95': ['ocd-division/country:us/state:ma/sldl:13th_essex'],
        '96': ['ocd-division/country:us/state:ma/sldl:14th_essex'],
        '97': ['ocd-division/country:us/state:ma/sldl:15th_essex'],
        '98': ['ocd-division/country:us/state:ma/sldl:16th_essex'],
        '99': ['ocd-division/country:us/state:ma/sldl:17th_essex'],
        '100': ['ocd-division/country:us/state:ma/sldl:1st_franklin'],
        '101': ['ocd-division/country:us/state:ma/sldl:2nd_franklin'],
        '102': ['ocd-division/country:us/state:ma/sldl:1st_hampden'],
        '103': ['ocd-division/country:us/state:ma/sldl:2nd_hampden'],
        '104': ['ocd-division/country:us/state:ma/sldl:3rd_hampden'],
        '105': ['ocd-division/country:us/state:ma/sldl:4th_hampden'],
        '106': ['ocd-division/country:us/state:ma/sldl:5th_hampden'],
        '107': ['ocd-division/country:us/state:ma/sldl:6th_hampden'],
        '108': ['ocd-division/country:us/state:ma/sldl:7th_hampden'],
        '109': ['ocd-division/country:us/state:ma/sldl:8th_hampden'],
        '110': ['ocd-division/country:us/state:ma/sldl:9th_hampden'],
        '111': ['ocd-division/country:us/state:ma/sldl:10th_hampden'],
        '112': ['ocd-division/country:us/state:ma/sldl:11th_hampden'],
        '113': ['ocd-division/country:us/state:ma/sldl:12th_hampden'],
        '114': ['ocd-division/country:us/state:ma/sldl:18th_essex'],
        '115': ['ocd-division/country:us/state:ma/sldl:1st_hampshire'],
        '116': ['ocd-division/country:us/state:ma/sldl:2nd_hampshire'],
        '117': ['ocd-division/country:us/state:ma/sldl:3rd_hampshire'],
        '118': ['ocd-division/country:us/state:ma/sldl:1st_middlesex'],
        '119': ['ocd-division/country:us/state:ma/sldl:2nd_middlesex'],
        '120': ['ocd-division/country:us/state:ma/sldl:3rd_middlesex'],
        '121': ['ocd-division/country:us/state:ma/sldl:4th_middlesex'],
        '122': ['ocd-division/country:us/state:ma/sldl:5th_middlesex'],
        '123': ['ocd-division/country:us/state:ma/sldl:6th_middlesex'],
        '124': ['ocd-division/country:us/state:ma/sldl:7th_middlesex'],
        '125': ['ocd-division/country:us/state:ma/sldl:8th_middlesex'],
        '126': ['ocd-division/country:us/state:ma/sldl:9th_middlesex'],
        '127': ['ocd-division/country:us/state:ma/sldl:10th_middlesex'],
        '128': ['ocd-division/country:us/state:ma/sldl:11th_middlesex'],
        '129': ['ocd-division/country:us/state:ma/sldl:12th_middlesex'],
        '130': ['ocd-division/country:us/state:ma/sldl:13th_middlesex'],
        '131': ['ocd-division/country:us/state:ma/sldl:14th_middlesex'],
        '132': ['ocd-division/country:us/state:ma/sldl:15th_middlesex'],
        '133': ['ocd-division/country:us/state:ma/sldl:16th_middlesex'],
        '134': ['ocd-division/country:us/state:ma/sldl:17th_middlesex'],
        '135': ['ocd-division/country:us/state:ma/sldl:18th_middlesex'],
        '136': ['ocd-division/country:us/state:ma/sldl:19th_middlesex'],
        '137': ['ocd-division/country:us/state:ma/sldl:20th_middlesex'],
        '138': ['ocd-division/country:us/state:ma/sldl:21st_middlesex'],
        '139': ['ocd-division/country:us/state:ma/sldl:22nd_middlesex'],
        '140': ['ocd-division/country:us/state:ma/sldl:23rd_middlesex'],
        '141': ['ocd-division/country:us/state:ma/sldl:24th_middlesex'],
        '142': ['ocd-division/country:us/state:ma/sldl:25th_middlesex'],
        '143': ['ocd-division/country:us/state:ma/sldl:26th_middlesex'],
        '144': ['ocd-division/country:us/state:ma/sldl:27th_middlesex'],
        '145': ['ocd-division/country:us/state:ma/sldl:28th_middlesex'],
        '146': ['ocd-division/country:us/state:ma/sldl:29th_middlesex'],
        '147': ['ocd-division/country:us/state:ma/sldl:30th_middlesex'],
        '148': ['ocd-division/country:us/state:ma/sldl:31st_middlesex'],
        '149': ['ocd-division/country:us/state:ma/sldl:32nd_middlesex'],
        '150': ['ocd-division/country:us/state:ma/sldl:33rd_middlesex'],
        '151': ['ocd-division/country:us/state:ma/sldl:34th_middlesex'],
        '152': ['ocd-division/country:us/state:ma/sldl:35th_middlesex'],
        '153': ['ocd-division/country:us/state:ma/sldl:36th_middlesex'],
        '154': ['ocd-division/country:us/state:ma/sldl:37th_middlesex'],
        '155': ['ocd-division/country:us/state:ma/sldl:18th_worcester'],
        '156': ['ocd-division/country:us/state:ma/sldl:5th_barnstable'],
        '157': ['ocd-division/country:us/state:ma/sldl:1st_norfolk'],
        '158': ['ocd-division/country:us/state:ma/sldl:2nd_norfolk'],
        '159': ['ocd-division/country:us/state:ma/sldl:3rd_norfolk'],
        '160': ['ocd-division/country:us/state:ma/sldl:4th_norfolk'],
        '161': ['ocd-division/country:us/state:ma/sldl:5th_norfolk'],
        '162': ['ocd-division/country:us/state:ma/sldl:6th_norfolk'],
        '163': ['ocd-division/country:us/state:ma/sldl:7th_norfolk'],
        '164': ['ocd-division/country:us/state:ma/sldl:8th_norfolk'],
        '165': ['ocd-division/country:us/state:ma/sldl:9th_norfolk'],
        '166': ['ocd-division/country:us/state:ma/sldl:10th_norfolk'],
        '167': ['ocd-division/country:us/state:ma/sldl:11th_norfolk'],
        '168': ['ocd-division/country:us/state:ma/sldl:12th_norfolk'],
        '169': ['ocd-division/country:us/state:ma/sldl:13th_norfolk'],
        '170': ['ocd-division/country:us/state:ma/sldl:14th_norfolk'],
        '171': ['ocd-division/country:us/state:ma/sldl:15th_norfolk'],
        '172': ['ocd-division/country:us/state:ma/sldl:1st_plymouth'],
        '173': ['ocd-division/country:us/state:ma/sldl:2nd_plymouth'],
        '174': ['ocd-division/country:us/state:ma/sldl:3rd_plymouth'],
        '175': ['ocd-division/country:us/state:ma/sldl:4th_plymouth'],
        '176': ['ocd-division/country:us/state:ma/sldl:5th_plymouth'],
        '177': ['ocd-division/country:us/state:ma/sldl:6th_plymouth'],
        '178': ['ocd-division/country:us/state:ma/sldl:7th_plymouth'],
        '179': ['ocd-division/country:us/state:ma/sldl:8th_plymouth'],
        '180': ['ocd-division/country:us/state:ma/sldl:9th_plymouth'],
        '181': ['ocd-division/country:us/state:ma/sldl:10th_plymouth'],
        '182': ['ocd-division/country:us/state:ma/sldl:11th_plymouth'],
        '183': ['ocd-division/country:us/state:ma/sldl:12th_plymouth'],
        '184': ['ocd-division/country:us/state:ma/sldl:1st_suffolk'],
        '185': ['ocd-division/country:us/state:ma/sldl:2nd_suffolk'],
        '186': ['ocd-division/country:us/state:ma/sldl:3rd_suffolk'],
        '187': ['ocd-division/country:us/state:ma/sldl:4th_suffolk'],
        '188': ['ocd-division/country:us/state:ma/sldl:5th_suffolk'],
        '189': ['ocd-division/country:us/state:ma/sldl:6th_suffolk'],
        '190': ['ocd-division/country:us/state:ma/sldl:7th_suffolk'],
        '191': ['ocd-division/country:us/state:ma/sldl:8th_suffolk'],
        '192': ['ocd-division/country:us/state:ma/sldl:9th_suffolk'],
        '193': ['ocd-division/country:us/state:ma/sldl:10th_suffolk'],
        '194': ['ocd-division/country:us/state:ma/sldl:11th_suffolk'],
        '195': ['ocd-division/country:us/state:ma/sldl:12th_suffolk'],
        '196': ['ocd-division/country:us/state:ma/sldl:13th_suffolk'],
        '197': ['ocd-division/country:us/state:ma/sldl:14th_suffolk'],
        '198': ['ocd-division/country:us/state:ma/sldl:15th_suffolk'],
        '199': ['ocd-division/country:us/state:ma/sldl:16th_suffolk'],
        '200': ['ocd-division/country:us/state:ma/sldl:17th_suffolk'],
        '201': ['ocd-division/country:us/state:ma/sldl:18th_suffolk'],
        '202': ['ocd-division/country:us/state:ma/sldl:19th_suffolk'],
        '203': ['ocd-division/country:us/state:ma/sldl:1st_worcester'],
        '204': ['ocd-division/country:us/state:ma/sldl:2nd_worcester'],
        '205': ['ocd-division/country:us/state:ma/sldl:3rd_worcester'],
        '206': ['ocd-division/country:us/state:ma/sldl:4th_worcester'],
        '207': ['ocd-division/country:us/state:ma/sldl:5th_worcester'],
        '208': ['ocd-division/country:us/state:ma/sldl:6th_worcester'],
        '209': ['ocd-division/country:us/state:ma/sldl:7th_worcester'],
        '210': ['ocd-division/country:us/state:ma/sldl:8th_worcester'],
        '211': ['ocd-division/country:us/state:ma/sldl:9th_worcester'],
        '212': ['ocd-division/country:us/state:ma/sldl:10th_worcester'],
        '213': ['ocd-division/country:us/state:ma/sldl:11th_worcester'],
        '214': ['ocd-division/country:us/state:ma/sldl:12th_worcester'],
        '215': ['ocd-division/country:us/state:ma/sldl:13th_worcester'],
        '216': ['ocd-division/country:us/state:ma/sldl:14th_worcester'],
        '217': ['ocd-division/country:us/state:ma/sldl:15th_worcester'],
        '218': ['ocd-division/country:us/state:ma/sldl:16th_worcester'],
        '219': ['ocd-division/country:us/state:ma/sldl:17th_worcester']
    },
    'MD': {
        '1A': ['ocd-division/country:us/state:md/sldl:1a'],
        '1B': ['ocd-division/country:us/state:md/sldl:1b'],
        '2A': ['ocd-division/country:us/state:md/sldl:2a'],
        '2B': ['ocd-division/country:us/state:md/sldl:2b'],
        '3A': ['ocd-division/country:us/state:md/sldl:3a'],
        '3B': ['ocd-division/country:us/state:md/sldl:3b'],
        '9A': ['ocd-division/country:us/state:md/sldl:9a'],
        '9B': ['ocd-division/country:us/state:md/sldl:9b'],
        '23A': ['ocd-division/country:us/state:md/sldl:23a'],
        '23B': ['ocd-division/country:us/state:md/sldl:23b'],
        '27A': ['ocd-division/country:us/state:md/sldl:27a'],
        '27B': ['ocd-division/country:us/state:md/sldl:27b'],
        '27C': ['ocd-division/country:us/state:md/sldl:27c'],
        '29A': ['ocd-division/country:us/state:md/sldl:29a'],
        '29B': ['ocd-division/country:us/state:md/sldl:29b'],
        '29C': ['ocd-division/country:us/state:md/sldl:29c'],
        '30A': ['ocd-division/country:us/state:md/sldl:30a'],
        '30B': ['ocd-division/country:us/state:md/sldl:30b'],
        '31A': ['ocd-division/country:us/state:md/sldl:31a'],
        '31B': ['ocd-division/country:us/state:md/sldl:31b'],
        '34A': ['ocd-division/country:us/state:md/sldl:34a'],
        '34B': ['ocd-division/country:us/state:md/sldl:34b'],
        '35A': ['ocd-division/country:us/state:md/sldl:35a'],
        '35B': ['ocd-division/country:us/state:md/sldl:35b'],
        '37A': ['ocd-division/country:us/state:md/sldl:37a'],
        '37B': ['ocd-division/country:us/state:md/sldl:37b'],
        '38A': ['ocd-division/country:us/state:md/sldl:38a'],
        '38B': ['ocd-division/country:us/state:md/sldl:38b'],
        '38C': ['ocd-division/country:us/state:md/sldl:38c'],
        '42A': ['ocd-division/country:us/state:md/sldl:42a'],
        '42B': ['ocd-division/country:us/state:md/sldl:42b'],
        '44A': ['ocd-division/country:us/state:md/sldl:44a'],
        '44B': ['ocd-division/country:us/state:md/sldl:44b'],
        '47A': ['ocd-division/country:us/state:md/sldl:47a'],
        '47B': ['ocd-division/country:us/state:md/sldl:47b']
    },
    'MN': {
        '1A': ['ocd-division/country:us/state:mn/sldl:1a'],
        '1B': ['ocd-division/country:us/state:mn/sldl:1b'],
        '2A': ['ocd-division/country:us/state:mn/sldl:2a'],
        '2B': ['ocd-division/country:us/state:mn/sldl:2b'],
        '3A': ['ocd-division/country:us/state:mn/sldl:3a'],
        '3B': ['ocd-division/country:us/state:mn/sldl:3b'],
        '4A': ['ocd-division/country:us/state:mn/sldl:4a'],
        '4B': ['ocd-division/country:us/state:mn/sldl:4b'],
        '5A': ['ocd-division/country:us/state:mn/sldl:5a'],
        '5B': ['ocd-division/country:us/state:mn/sldl:5b'],
        '6A': ['ocd-division/country:us/state:mn/sldl:6a'],
        '6B': ['ocd-division/country:us/state:mn/sldl:6b'],
        '7A': ['ocd-division/country:us/state:mn/sldl:7a'],
        '7B': ['ocd-division/country:us/state:mn/sldl:7b'],
        '8A': ['ocd-division/country:us/state:mn/sldl:8a'],
        '8B': ['ocd-division/country:us/state:mn/sldl:8b'],
        '9A': ['ocd-division/country:us/state:mn/sldl:9a'],
        '9B': ['ocd-division/country:us/state:mn/sldl:9b'],
        '10A': ['ocd-division/country:us/state:mn/sldl:10a'],
        '10B': ['ocd-division/country:us/state:mn/sldl:10b'],
        '11A': ['ocd-division/country:us/state:mn/sldl:11a'],
        '11B': ['ocd-division/country:us/state:mn/sldl:11b'],
        '12A': ['ocd-division/country:us/state:mn/sldl:12a'],
        '12B': ['ocd-division/country:us/state:mn/sldl:12b'],
        '13A': ['ocd-division/country:us/state:mn/sldl:13a'],
        '13B': ['ocd-division/country:us/state:mn/sldl:13b'],
        '14A': ['ocd-division/country:us/state:mn/sldl:14a'],
        '14B': ['ocd-division/country:us/state:mn/sldl:14b'],
        '15A': ['ocd-division/country:us/state:mn/sldl:15a'],
        '15B': ['ocd-division/country:us/state:mn/sldl:15b'],
        '16A': ['ocd-division/country:us/state:mn/sldl:16a'],
        '16B': ['ocd-division/country:us/state:mn/sldl:16b'],
        '17A': ['ocd-division/country:us/state:mn/sldl:17a'],
        '17B': ['ocd-division/country:us/state:mn/sldl:17b'],
        '18A': ['ocd-division/country:us/state:mn/sldl:18a'],
        '18B': ['ocd-division/country:us/state:mn/sldl:18b'],
        '19A': ['ocd-division/country:us/state:mn/sldl:19a'],
        '19B': ['ocd-division/country:us/state:mn/sldl:19b'],
        '20A': ['ocd-division/country:us/state:mn/sldl:20a'],
        '20B': ['ocd-division/country:us/state:mn/sldl:20b'],
        '21A': ['ocd-division/country:us/state:mn/sldl:21a'],
        '21B': ['ocd-division/country:us/state:mn/sldl:21b'],
        '22A': ['ocd-division/country:us/state:mn/sldl:22a'],
        '22B': ['ocd-division/country:us/state:mn/sldl:22b'],
        '23A': ['ocd-division/country:us/state:mn/sldl:23a'],
        '23B': ['ocd-division/country:us/state:mn/sldl:23b'],
        '24A': ['ocd-division/country:us/state:mn/sldl:24a'],
        '24B': ['ocd-division/country:us/state:mn/sldl:24b'],
        '25A': ['ocd-division/country:us/state:mn/sldl:25a'],
        '25B': ['ocd-division/country:us/state:mn/sldl:25b'],
        '26A': ['ocd-division/country:us/state:mn/sldl:26a'],
        '26B': ['ocd-division/country:us/state:mn/sldl:26b'],
        '27A': ['ocd-division/country:us/state:mn/sldl:27a'],
        '27B': ['ocd-division/country:us/state:mn/sldl:27b'],
        '28A': ['ocd-division/country:us/state:mn/sldl:28a'],
        '28B': ['ocd-division/country:us/state:mn/sldl:28b'],
        '29A': ['ocd-division/country:us/state:mn/sldl:29a'],
        '29B': ['ocd-division/country:us/state:mn/sldl:29b'],
        '30A': ['ocd-division/country:us/state:mn/sldl:30a'],
        '30B': ['ocd-division/country:us/state:mn/sldl:30b'],
        '31A': ['ocd-division/country:us/state:mn/sldl:31a'],
        '31B': ['ocd-division/country:us/state:mn/sldl:31b'],
        '32A': ['ocd-division/country:us/state:mn/sldl:32a'],
        '32B': ['ocd-division/country:us/state:mn/sldl:32b'],
        '33A': ['ocd-division/country:us/state:mn/sldl:33a'],
        '33B': ['ocd-division/country:us/state:mn/sldl:33b'],
        '34A': ['ocd-division/country:us/state:mn/sldl:34a'],
        '34B': ['ocd-division/country:us/state:mn/sldl:34b'],
        '35A': ['ocd-division/country:us/state:mn/sldl:35a'],
        '35B': ['ocd-division/country:us/state:mn/sldl:35b'],
        '36A': ['ocd-division/country:us/state:mn/sldl:36a'],
        '36B': ['ocd-division/country:us/state:mn/sldl:36b'],
        '37A': ['ocd-division/country:us/state:mn/sldl:37a'],
        '37B': ['ocd-division/country:us/state:mn/sldl:37b'],
        '38A': ['ocd-division/country:us/state:mn/sldl:38a'],
        '38B': ['ocd-division/country:us/state:mn/sldl:38b'],
        '39A': ['ocd-division/country:us/state:mn/sldl:39a'],
        '39B': ['ocd-division/country:us/state:mn/sldl:39b'],
        '40A': ['ocd-division/country:us/state:mn/sldl:40a'],
        '40B': ['ocd-division/country:us/state:mn/sldl:40b'],
        '41A': ['ocd-division/country:us/state:mn/sldl:41a'],
        '41B': ['ocd-division/country:us/state:mn/sldl:41b'],
        '42A': ['ocd-division/country:us/state:mn/sldl:42a'],
        '42B': ['ocd-division/country:us/state:mn/sldl:42b'],
        '43A': ['ocd-division/country:us/state:mn/sldl:43a'],
        '43B': ['ocd-division/country:us/state:mn/sldl:43b'],
        '44A': ['ocd-division/country:us/state:mn/sldl:44a'],
        '44B': ['ocd-division/country:us/state:mn/sldl:44b'],
        '45A': ['ocd-division/country:us/state:mn/sldl:45a'],
        '45B': ['ocd-division/country:us/state:mn/sldl:45b'],
        '46A': ['ocd-division/country:us/state:mn/sldl:46a'],
        '46B': ['ocd-division/country:us/state:mn/sldl:46b'],
        '47A': ['ocd-division/country:us/state:mn/sldl:47a'],
        '47B': ['ocd-division/country:us/state:mn/sldl:47b'],
        '48A': ['ocd-division/country:us/state:mn/sldl:48a'],
        '48B': ['ocd-division/country:us/state:mn/sldl:48b'],
        '49A': ['ocd-division/country:us/state:mn/sldl:49a'],
        '49B': ['ocd-division/country:us/state:mn/sldl:49b'],
        '50A': ['ocd-division/country:us/state:mn/sldl:50a'],
        '50B': ['ocd-division/country:us/state:mn/sldl:50b'],
        '51A': ['ocd-division/country:us/state:mn/sldl:51a'],
        '51B': ['ocd-division/country:us/state:mn/sldl:51b'],
        '52A': ['ocd-division/country:us/state:mn/sldl:52a'],
        '52B': ['ocd-division/country:us/state:mn/sldl:52b'],
        '53A': ['ocd-division/country:us/state:mn/sldl:53a'],
        '53B': ['ocd-division/country:us/state:mn/sldl:53b'],
        '54A': ['ocd-division/country:us/state:mn/sldl:54a'],
        '54B': ['ocd-division/country:us/state:mn/sldl:54b'],
        '55A': ['ocd-division/country:us/state:mn/sldl:55a'],
        '55B': ['ocd-division/country:us/state:mn/sldl:55b'],
        '56A': ['ocd-division/country:us/state:mn/sldl:56a'],
        '56B': ['ocd-division/country:us/state:mn/sldl:56b'],
        '57A': ['ocd-division/country:us/state:mn/sldl:57a'],
        '57B': ['ocd-division/country:us/state:mn/sldl:57b'],
        '58A': ['ocd-division/country:us/state:mn/sldl:58a'],
        '58B': ['ocd-division/country:us/state:mn/sldl:58b'],
        '59A': ['ocd-division/country:us/state:mn/sldl:59a'],
        '59B': ['ocd-division/country:us/state:mn/sldl:59b'],
        '60A': ['ocd-division/country:us/state:mn/sldl:60a'],
        '60B': ['ocd-division/country:us/state:mn/sldl:60b'],
        '61A': ['ocd-division/country:us/state:mn/sldl:61a'],
        '61B': ['ocd-division/country:us/state:mn/sldl:61b'],
        '62A': ['ocd-division/country:us/state:mn/sldl:62a'],
        '62B': ['ocd-division/country:us/state:mn/sldl:62b'],
        '63A': ['ocd-division/country:us/state:mn/sldl:63a'],
        '63B': ['ocd-division/country:us/state:mn/sldl:63b'],
        '64A': ['ocd-division/country:us/state:mn/sldl:64a'],
        '64B': ['ocd-division/country:us/state:mn/sldl:64b'],
        '65A': ['ocd-division/country:us/state:mn/sldl:65a'],
        '65B': ['ocd-division/country:us/state:mn/sldl:65b'],
        '66A': ['ocd-division/country:us/state:mn/sldl:66a'],
        '66B': ['ocd-division/country:us/state:mn/sldl:66b'],
        '67A': ['ocd-division/country:us/state:mn/sldl:67a'],
        '67B': ['ocd-division/country:us/state:mn/sldl:67b']
    },
    'NH': {
        '1': ['ocd-division/country:us/state:nh/sldl:belknap_1'],
        '2': ['ocd-division/country:us/state:nh/sldl:belknap_2'],
        '3': ['ocd-division/country:us/state:nh/sldl:belknap_3',
              'ocd-division/country:us/state:nh/sldl:belknap_9'],
        '4': ['ocd-division/country:us/state:nh/sldl:belknap_4'],
        '5': ['ocd-division/country:us/state:nh/sldl:belknap_5',
              'ocd-division/country:us/state:nh/sldl:belknap_8'],
        '6': ['ocd-division/country:us/state:nh/sldl:belknap_6',
              'ocd-division/country:us/state:nh/sldl:belknap_9'],
        '7': ['ocd-division/country:us/state:nh/sldl:belknap_7',
              'ocd-division/country:us/state:nh/sldl:belknap_8'],
        '101': ['ocd-division/country:us/state:nh/sldl:carroll_1',
                'ocd-division/country:us/state:nh/sldl:carroll_7'],
        '102': ['ocd-division/country:us/state:nh/sldl:carroll_2',
                'ocd-division/country:us/state:nh/sldl:carroll_7'],
        '103': ['ocd-division/country:us/state:nh/sldl:carroll_3',
                 'ocd-division/country:us/state:nh/sldl:carroll_7'],
        '104': ['ocd-division/country:us/state:nh/sldl:carroll_4',
                'ocd-division/country:us/state:nh/sldl:carroll_8'],
        '105': ['ocd-division/country:us/state:nh/sldl:carroll_5',
                'ocd-division/country:us/state:nh/sldl:carroll_8'],
        '106': ['ocd-division/country:us/state:nh/sldl:carroll_6'],
        '201': ['ocd-division/country:us/state:nh/sldl:cheshire_1'],
        '202': ['ocd-division/country:us/state:nh/sldl:cheshire_2'],
        '203': ['ocd-division/country:us/state:nh/sldl:cheshire_3'],
        '204': ['ocd-division/country:us/state:nh/sldl:cheshire_4',
                'ocd-division/country:us/state:nh/sldl:cheshire_16'],
        '205': ['ocd-division/country:us/state:nh/sldl:cheshire_5',
                'ocd-division/country:us/state:nh/sldl:cheshire_16'],
        '206': ['ocd-division/country:us/state:nh/sldl:cheshire_6',
                'ocd-division/country:us/state:nh/sldl:cheshire_16'],
        '207': ['ocd-division/country:us/state:nh/sldl:cheshire_7',
                'ocd-division/country:us/state:nh/sldl:cheshire_16'],
        '208': ['ocd-division/country:us/state:nh/sldl:cheshire_8',
                'ocd-division/country:us/state:nh/sldl:cheshire_16'],
        '209': ['ocd-division/country:us/state:nh/sldl:cheshire_9',
                'ocd-division/country:us/state:nh/sldl:cheshire_14'],
        '210': ['ocd-division/country:us/state:nh/sldl:cheshire_10',
                'ocd-division/country:us/state:nh/sldl:cheshire_15'],
        '211': ['ocd-division/country:us/state:nh/sldl:cheshire_11',
                'ocd-division/country:us/state:nh/sldl:cheshire_14'],
        '212': ['ocd-division/country:us/state:nh/sldl:cheshire_12',
                'ocd-division/country:us/state:nh/sldl:cheshire_15'],
        '213': ['ocd-division/country:us/state:nh/sldl:cheshire_13',
                'ocd-division/country:us/state:nh/sldl:cheshire_15'],
        '301': ['ocd-division/country:us/state:nh/sldl:coos_1'],
        '302': ['ocd-division/country:us/state:nh/sldl:coos_2',
                'ocd-division/country:us/state:nh/sldl:coos_7'],
        '303': ['ocd-division/country:us/state:nh/sldl:coos_3'],
        '304': ['ocd-division/country:us/state:nh/sldl:coos_4',
                'ocd-division/country:us/state:nh/sldl:coos_7'],
        '305': ['ocd-division/country:us/state:nh/sldl:coos_5',
                'ocd-division/country:us/state:nh/sldl:coos_7'],
        '306': ['ocd-division/country:us/state:nh/sldl:coos_6'],
        '401': ['ocd-division/country:us/state:nh/sldl:grafton_1',
                'ocd-division/country:us/state:nh/sldl:grafton_14'],
        '402': ['ocd-division/country:us/state:nh/sldl:grafton_2',
                'ocd-division/country:us/state:nh/sldl:grafton_14'],
        '403': ['ocd-division/country:us/state:nh/sldl:grafton_3',
                'ocd-division/country:us/state:nh/sldl:grafton_15'],
        '404': ['ocd-division/country:us/state:nh/sldl:grafton_4',
                'ocd-division/country:us/state:nh/sldl:grafton_15'],
        '405': ['ocd-division/country:us/state:nh/sldl:grafton_5'],
        '406': ['ocd-division/country:us/state:nh/sldl:grafton_6',
                'ocd-division/country:us/state:nh/sldl:grafton_16'],
        '407': ['ocd-division/country:us/state:nh/sldl:grafton_7'],
        '408': ['ocd-division/country:us/state:nh/sldl:grafton_8'],
        '409': ['ocd-division/country:us/state:nh/sldl:grafton_9',
                'ocd-division/country:us/state:nh/sldl:grafton_17'],
        '410': ['ocd-division/country:us/state:nh/sldl:grafton_10',
                'ocd-division/country:us/state:nh/sldl:grafton_17'],
        '411': ['ocd-division/country:us/state:nh/sldl:grafton_11',
                'ocd-division/country:us/state:nh/sldl:grafton_16'],
        '412': ['ocd-division/country:us/state:nh/sldl:grafton_12'],
        '413': ['ocd-division/country:us/state:nh/sldl:grafton_13'],
        '501': ['ocd-division/country:us/state:nh/sldl:hillsborough_1',
                'ocd-division/country:us/state:nh/sldl:hillsborough_38'],
        '502': ['ocd-division/country:us/state:nh/sldl:hillsborough_2',
                'ocd-division/country:us/state:nh/sldl:hillsborough_39'],
        '503': ['ocd-division/country:us/state:nh/sldl:hillsborough_3',
                'ocd-division/country:us/state:nh/sldl:hillsborough_38'],
        '504': ['ocd-division/country:us/state:nh/sldl:hillsborough_4',
                'ocd-division/country:us/state:nh/sldl:hillsborough_38'],
        '505': ['ocd-division/country:us/state:nh/sldl:hillsborough_5',
                'ocd-division/country:us/state:nh/sldl:hillsborough_40'],
        '506': ['ocd-division/country:us/state:nh/sldl:hillsborough_6',
                'ocd-division/country:us/state:nh/sldl:hillsborough_39'],
        '507': ['ocd-division/country:us/state:nh/sldl:hillsborough_7',
                'ocd-division/country:us/state:nh/sldl:hillsborough_41'],
        '508': ['ocd-division/country:us/state:nh/sldl:hillsborough_8',
                'ocd-division/country:us/state:nh/sldl:hillsborough_42'],
        '509': ['ocd-division/country:us/state:nh/sldl:hillsborough_9',
                'ocd-division/country:us/state:nh/sldl:hillsborough_42'],
        '510': ['ocd-division/country:us/state:nh/sldl:hillsborough_10',
                'ocd-division/country:us/state:nh/sldl:hillsborough_42'],
        '511': ['ocd-division/country:us/state:nh/sldl:hillsborough_11',
                'ocd-division/country:us/state:nh/sldl:hillsborough_43'],
        '512': ['ocd-division/country:us/state:nh/sldl:hillsborough_12',
                'ocd-division/country:us/state:nh/sldl:hillsborough_43'],
        '513': ['ocd-division/country:us/state:nh/sldl:hillsborough_13',
                'ocd-division/country:us/state:nh/sldl:hillsborough_43'],
        '514': ['ocd-division/country:us/state:nh/sldl:hillsborough_14',
                'ocd-division/country:us/state:nh/sldl:hillsborough_43'],
        '515': ['ocd-division/country:us/state:nh/sldl:hillsborough_15',
                'ocd-division/country:us/state:nh/sldl:hillsborough_44'],
        '516': ['ocd-division/country:us/state:nh/sldl:hillsborough_16',
                'ocd-division/country:us/state:nh/sldl:hillsborough_44'],
        '517': ['ocd-division/country:us/state:nh/sldl:hillsborough_17',
                'ocd-division/country:us/state:nh/sldl:hillsborough_45'],
        '518': ['ocd-division/country:us/state:nh/sldl:hillsborough_18',
                'ocd-division/country:us/state:nh/sldl:hillsborough_45'],
        '519': ['ocd-division/country:us/state:nh/sldl:hillsborough_19',
                'ocd-division/country:us/state:nh/sldl:hillsborough_45'],
        '520': ['ocd-division/country:us/state:nh/sldl:hillsborough_20',
                'ocd-division/country:us/state:nh/sldl:hillsborough_44'],
        '521': ['ocd-division/country:us/state:nh/sldl:hillsborough_21'],
        '522': ['ocd-division/country:us/state:nh/sldl:hillsborough_22',
                'ocd-division/country:us/state:nh/sldl:hillsborough_41'],
        '523': ['ocd-division/country:us/state:nh/sldl:hillsborough_23',
                'ocd-division/country:us/state:nh/sldl:hillsborough_40'],
        '524': ['ocd-division/country:us/state:nh/sldl:hillsborough_24'],
        '525': ['ocd-division/country:us/state:nh/sldl:hillsborough_25'],
        '526': ['ocd-division/country:us/state:nh/sldl:hillsborough_26'],
        '527': ['ocd-division/country:us/state:nh/sldl:hillsborough_27',
                'ocd-division/country:us/state:nh/sldl:hillsborough_40'],
        '528': ['ocd-division/country:us/state:nh/sldl:hillsborough_28'],
        '529': ['ocd-division/country:us/state:nh/sldl:hillsborough_29'],
        '530': ['ocd-division/country:us/state:nh/sldl:hillsborough_30'],
        '531': ['ocd-division/country:us/state:nh/sldl:hillsborough_31'],
        '532': ['ocd-division/country:us/state:nh/sldl:hillsborough_32'],
        '533': ['ocd-division/country:us/state:nh/sldl:hillsborough_33'],
        '534': ['ocd-division/country:us/state:nh/sldl:hillsborough_34'],
        '535': ['ocd-division/country:us/state:nh/sldl:hillsborough_35'],
        '536': ['ocd-division/country:us/state:nh/sldl:hillsborough_36'],
        '537': ['ocd-division/country:us/state:nh/sldl:hillsborough_37'],
        '601': ['ocd-division/country:us/state:nh/sldl:merrimack_1',
                'ocd-division/country:us/state:nh/sldl:merrimack_25'],
        '602': ['ocd-division/country:us/state:nh/sldl:merrimack_2'],
        '603': ['ocd-division/country:us/state:nh/sldl:merrimack_3',
                'ocd-division/country:us/state:nh/sldl:merrimack_26'],
        '604': ['ocd-division/country:us/state:nh/sldl:merrimack_4'],
        '605': ['ocd-division/country:us/state:nh/sldl:merrimack_5'],
        '606': ['ocd-division/country:us/state:nh/sldl:merrimack_6'],
        '607': ['ocd-division/country:us/state:nh/sldl:merrimack_7',
                'ocd-division/country:us/state:nh/sldl:merrimack_25'],
        '608': ['ocd-division/country:us/state:nh/sldl:merrimack_8',
                'ocd-division/country:us/state:nh/sldl:merrimack_26'],
        '609': ['ocd-division/country:us/state:nh/sldl:merrimack_9',
                'ocd-division/country:us/state:nh/sldl:merrimack_26'],
        '610': ['ocd-division/country:us/state:nh/sldl:merrimack_10'],
        '611': ['ocd-division/country:us/state:nh/sldl:merrimack_11',
                'ocd-division/country:us/state:nh/sldl:merrimack_27'],
        '612': ['ocd-division/country:us/state:nh/sldl:merrimack_12',
                'ocd-division/country:us/state:nh/sldl:merrimack_27'],
        '613': ['ocd-division/country:us/state:nh/sldl:merrimack_13',
                'ocd-division/country:us/state:nh/sldl:merrimack_27'],
        '614': ['ocd-division/country:us/state:nh/sldl:merrimack_14',
                'ocd-division/country:us/state:nh/sldl:merrimack_27'],
        '615': ['ocd-division/country:us/state:nh/sldl:merrimack_15',
                'ocd-division/country:us/state:nh/sldl:merrimack_27'],
        '616': ['ocd-division/country:us/state:nh/sldl:merrimack_16',
                'ocd-division/country:us/state:nh/sldl:merrimack_27'],
        '617': ['ocd-division/country:us/state:nh/sldl:merrimack_17',
                'ocd-division/country:us/state:nh/sldl:merrimack_28'],
        '618': ['ocd-division/country:us/state:nh/sldl:merrimack_18',
                'ocd-division/country:us/state:nh/sldl:merrimack_28'],
        '619': ['ocd-division/country:us/state:nh/sldl:merrimack_19',
                'ocd-division/country:us/state:nh/sldl:merrimack_28'],
        '620': ['ocd-division/country:us/state:nh/sldl:merrimack_20'],
        '621': ['ocd-division/country:us/state:nh/sldl:merrimack_21',
                'ocd-division/country:us/state:nh/sldl:merrimack_29'],
        '622': ['ocd-division/country:us/state:nh/sldl:merrimack_22',
                'ocd-division/country:us/state:nh/sldl:merrimack_29'],
        '623': ['ocd-division/country:us/state:nh/sldl:merrimack_23'],
        '624': ['ocd-division/country:us/state:nh/sldl:merrimack_24'],
        '701': ['ocd-division/country:us/state:nh/sldl:rockingham_1',
                'ocd-division/country:us/state:nh/sldl:rockingham_32'],
        '702': ['ocd-division/country:us/state:nh/sldl:rockingham_2',
                'ocd-division/country:us/state:nh/sldl:rockingham_32'],
        '703': ['ocd-division/country:us/state:nh/sldl:rockingham_3'],
        '704': ['ocd-division/country:us/state:nh/sldl:rockingham_4'],
        '705': ['ocd-division/country:us/state:nh/sldl:rockingham_5'],
        '706': ['ocd-division/country:us/state:nh/sldl:rockingham_6'],
        '707': ['ocd-division/country:us/state:nh/sldl:rockingham_7'],
        '708': ['ocd-division/country:us/state:nh/sldl:rockingham_8'],
        '709': ['ocd-division/country:us/state:nh/sldl:rockingham_9'],
        '710': ['ocd-division/country:us/state:nh/sldl:rockingham_10',
                'ocd-division/country:us/state:nh/sldl:rockingham_33'],
        '711': ['ocd-division/country:us/state:nh/sldl:rockingham_11',
                'ocd-division/country:us/state:nh/sldl:rockingham_33'],
        '712': ['ocd-division/country:us/state:nh/sldl:rockingham_12',
                'ocd-division/country:us/state:nh/sldl:rockingham_33'],
        '713': ['ocd-division/country:us/state:nh/sldl:rockingham_13',
                'ocd-division/country:us/state:nh/sldl:rockingham_34'],
        '714': ['ocd-division/country:us/state:nh/sldl:rockingham_14',
                'ocd-division/country:us/state:nh/sldl:rockingham_34'],
        '715': ['ocd-division/country:us/state:nh/sldl:rockingham_15',
                'ocd-division/country:us/state:nh/sldl:rockingham_35'],
        '716': ['ocd-division/country:us/state:nh/sldl:rockingham_16',
                'ocd-division/country:us/state:nh/sldl:rockingham_35'],
        '717': ['ocd-division/country:us/state:nh/sldl:rockingham_17',
                'ocd-division/country:us/state:nh/sldl:rockingham_36'],
        '718': ['ocd-division/country:us/state:nh/sldl:rockingham_18',
                'ocd-division/country:us/state:nh/sldl:rockingham_36'],
        '719': ['ocd-division/country:us/state:nh/sldl:rockingham_19',
                'ocd-division/country:us/state:nh/sldl:rockingham_36'],
        '720': ['ocd-division/country:us/state:nh/sldl:rockingham_20',
                'ocd-division/country:us/state:nh/sldl:rockingham_37'],
        '721': ['ocd-division/country:us/state:nh/sldl:rockingham_21',
                'ocd-division/country:us/state:nh/sldl:rockingham_37'],
        '722': ['ocd-division/country:us/state:nh/sldl:rockingham_22',
                'ocd-division/country:us/state:nh/sldl:rockingham_31'],
        '723': ['ocd-division/country:us/state:nh/sldl:rockingham_23',
                'ocd-division/country:us/state:nh/sldl:rockingham_31'],
        '724': ['ocd-division/country:us/state:nh/sldl:rockingham_24'],
        '725': ['ocd-division/country:us/state:nh/sldl:rockingham_25',
                'ocd-division/country:us/state:nh/sldl:rockingham_30'],
        '726': ['ocd-division/country:us/state:nh/sldl:rockingham_26',
                'ocd-division/country:us/state:nh/sldl:rockingham_30'],
        '727': ['ocd-division/country:us/state:nh/sldl:rockingham_27',
                'ocd-division/country:us/state:nh/sldl:rockingham_31'],
        '728': ['ocd-division/country:us/state:nh/sldl:rockingham_28',
                'ocd-division/country:us/state:nh/sldl:rockingham_30'],
        '729': ['ocd-division/country:us/state:nh/sldl:rockingham_29',
                'ocd-division/country:us/state:nh/sldl:rockingham_30'],
        '801': ['ocd-division/country:us/state:nh/sldl:strafford_1'],
        '802': ['ocd-division/country:us/state:nh/sldl:strafford_2'],
        '803': ['ocd-division/country:us/state:nh/sldl:strafford_3'],
        '804': ['ocd-division/country:us/state:nh/sldl:strafford_4',
                'ocd-division/country:us/state:nh/sldl:strafford_25'],
        '805': ['ocd-division/country:us/state:nh/sldl:strafford_5',
                'ocd-division/country:us/state:nh/sldl:strafford_25'],
        '806': ['ocd-division/country:us/state:nh/sldl:strafford_6'],
        '807': ['ocd-division/country:us/state:nh/sldl:strafford_7',
                'ocd-division/country:us/state:nh/sldl:strafford_22'],
        '808': ['ocd-division/country:us/state:nh/sldl:strafford_8',
                'ocd-division/country:us/state:nh/sldl:strafford_22'],
        '809': ['ocd-division/country:us/state:nh/sldl:strafford_9',
                'ocd-division/country:us/state:nh/sldl:strafford_23'],
        '810': ['ocd-division/country:us/state:nh/sldl:strafford_10',
                'ocd-division/country:us/state:nh/sldl:strafford_23'],
        '811': ['ocd-division/country:us/state:nh/sldl:strafford_11',
                'ocd-division/country:us/state:nh/sldl:strafford_24'],
        '812': ['ocd-division/country:us/state:nh/sldl:strafford_12',
                'ocd-division/country:us/state:nh/sldl:strafford_24'],
        '813': ['ocd-division/country:us/state:nh/sldl:strafford_13',
                'ocd-division/country:us/state:nh/sldl:strafford_19'],
        '814': ['ocd-division/country:us/state:nh/sldl:strafford_14',
                'ocd-division/country:us/state:nh/sldl:strafford_19'],
        '815': ['ocd-division/country:us/state:nh/sldl:strafford_15',
                'ocd-division/country:us/state:nh/sldl:strafford_20'],
        '816': ['ocd-division/country:us/state:nh/sldl:strafford_16',
                'ocd-division/country:us/state:nh/sldl:strafford_20'],
        '817': ['ocd-division/country:us/state:nh/sldl:strafford_17',
                'ocd-division/country:us/state:nh/sldl:strafford_21'],
        '818': ['ocd-division/country:us/state:nh/sldl:strafford_18',
                'ocd-division/country:us/state:nh/sldl:strafford_21'],
        '901': ['ocd-division/country:us/state:nh/sldl:sullivan_1',
                'ocd-division/country:us/state:nh/sldl:sullivan_9'],
        '902': ['ocd-division/country:us/state:nh/sldl:sullivan_2',
                'ocd-division/country:us/state:nh/sldl:sullivan_9'],
        '903': ['ocd-division/country:us/state:nh/sldl:sullivan_3',
                'ocd-division/country:us/state:nh/sldl:sullivan_10'],
        '904': ['ocd-division/country:us/state:nh/sldl:sullivan_4',
                'ocd-division/country:us/state:nh/sldl:sullivan_10'],
        '905': ['ocd-division/country:us/state:nh/sldl:sullivan_5',
                'ocd-division/country:us/state:nh/sldl:sullivan_10'],
        '906': ['ocd-division/country:us/state:nh/sldl:sullivan_6',
                'ocd-division/country:us/state:nh/sldl:sullivan_9'],
        '907': ['ocd-division/country:us/state:nh/sldl:sullivan_7',
                'ocd-division/country:us/state:nh/sldl:sullivan_11'],
        '908': ['ocd-division/country:us/state:nh/sldl:sullivan_8',
                'ocd-division/country:us/state:nh/sldl:sullivan_11']
    },
    'SD': {
        '26A': ['ocd-division/country:us/state:sd/sldl:26a'],
        '26B': ['ocd-division/country:us/state:sd/sldl:26b'],
        '28A': ['ocd-division/country:us/state:sd/sldl:28a'],
        '28B': ['ocd-division/country:us/state:sd/sldl:28b']
    },
    'VT': {
        'A-1': ['ocd-division/country:us/state:vt/sldl:addison-1'],
        'A-2': ['ocd-division/country:us/state:vt/sldl:addison-2'],
        'A-3': ['ocd-division/country:us/state:vt/sldl:addison-3'],
        'A-4': ['ocd-division/country:us/state:vt/sldl:addison-4'],
        'A-5': ['ocd-division/country:us/state:vt/sldl:addison-5'],
        'A-R': ['ocd-division/country:us/state:vt/sldl:addison-rutland'],
        'B-1': ['ocd-division/country:us/state:vt/sldl:bennington-1'],
        'B-3': ['ocd-division/country:us/state:vt/sldl:bennington-3'],
        'B-4': ['ocd-division/country:us/state:vt/sldl:bennington-4'],
        'B-R': ['ocd-division/country:us/state:vt/sldl:bennington-rutland'],
        'B21': ['ocd-division/country:us/state:vt/sldl:bennington-2-1'],
        'B22': ['ocd-division/country:us/state:vt/sldl:bennington-2-2'],
        'C-1': ['ocd-division/country:us/state:vt/sldl:chittenden-1'],
        'C-2': ['ocd-division/country:us/state:vt/sldl:chittenden-2'],
        'C-3': ['ocd-division/country:us/state:vt/sldl:chittenden-3'],
        'C10': ['ocd-division/country:us/state:vt/sldl:chittenden-10'],
        'C41': ['ocd-division/country:us/state:vt/sldl:chittenden-4-1'],
        'C42': ['ocd-division/country:us/state:vt/sldl:chittenden-4-2'],
        'C51': ['ocd-division/country:us/state:vt/sldl:chittenden-5-1'],
        'C52': ['ocd-division/country:us/state:vt/sldl:chittenden-5-2'],
        'C61': ['ocd-division/country:us/state:vt/sldl:chittenden-6-1'],
        'C62': ['ocd-division/country:us/state:vt/sldl:chittenden-6-2'],
        'C63': ['ocd-division/country:us/state:vt/sldl:chittenden-6-3'],
        'C64': ['ocd-division/country:us/state:vt/sldl:chittenden-6-4'],
        'C65': ['ocd-division/country:us/state:vt/sldl:chittenden-6-5'],
        'C66': ['ocd-division/country:us/state:vt/sldl:chittenden-6-6'],
        'C67': ['ocd-division/country:us/state:vt/sldl:chittenden-6-7'],
        'C71': ['ocd-division/country:us/state:vt/sldl:chittenden-7-1'],
        'C72': ['ocd-division/country:us/state:vt/sldl:chittenden-7-2'],
        'C73': ['ocd-division/country:us/state:vt/sldl:chittenden-7-3'],
        'C74': ['ocd-division/country:us/state:vt/sldl:chittenden-7-4'],
        'C81': ['ocd-division/country:us/state:vt/sldl:chittenden-8-1'],
        'C82': ['ocd-division/country:us/state:vt/sldl:chittenden-8-2'],
        'C83': ['ocd-division/country:us/state:vt/sldl:chittenden-8-3'],
        'C91': ['ocd-division/country:us/state:vt/sldl:chittenden-9-1'],
        'C92': ['ocd-division/country:us/state:vt/sldl:chittenden-9-2'],
        'CA1': ['ocd-division/country:us/state:vt/sldl:caledonia-1'],
        'CA2': ['ocd-division/country:us/state:vt/sldl:caledonia-2'],
        'CA3': ['ocd-division/country:us/state:vt/sldl:caledonia-3'],
        'CA4': ['ocd-division/country:us/state:vt/sldl:caledonia-4'],
        'CAW': ['ocd-division/country:us/state:vt/sldl:caledonia-washington'],
        'E-C': ['ocd-division/country:us/state:vt/sldl:essex-caledonia'],
        'ECO': ['ocd-division/country:us/state:vt/sldl:essex-caledonia-orleans'],
        'F-1': ['ocd-division/country:us/state:vt/sldl:franklin-1'],
        'F-2': ['ocd-division/country:us/state:vt/sldl:franklin-2'],
        'F-4': ['ocd-division/country:us/state:vt/sldl:franklin-4'],
        'F-5': ['ocd-division/country:us/state:vt/sldl:franklin-5'],
        'F-6': ['ocd-division/country:us/state:vt/sldl:franklin-6'],
        'F-7': ['ocd-division/country:us/state:vt/sldl:franklin-7'],
        'F31': ['ocd-division/country:us/state:vt/sldl:franklin-3-1'],
        'F32': ['ocd-division/country:us/state:vt/sldl:franklin-3-2'],
        'GIC': ['ocd-division/country:us/state:vt/sldl:grand_isle-chittenden'],
        'LM1': ['ocd-division/country:us/state:vt/sldl:lamoille-1'],
        'LM2': ['ocd-division/country:us/state:vt/sldl:lamoille-2'],
        'LM3': ['ocd-division/country:us/state:vt/sldl:lamoille-3'],
        'LMW': ['ocd-division/country:us/state:vt/sldl:lamoille-washington'],
        'O-1': ['ocd-division/country:us/state:vt/sldl:orleans-1'],
        'O-2': ['ocd-division/country:us/state:vt/sldl:orleans-2'],
        'O-C': ['ocd-division/country:us/state:vt/sldl:orange-caledonia'],
        'O-L': ['ocd-division/country:us/state:vt/sldl:orleans-lamoille'],
        'OLC': ['ocd-division/country:us/state:vt/sldl:orleans-caledonia'],
        'OR1': ['ocd-division/country:us/state:vt/sldl:orange-1'],
        'OR2': ['ocd-division/country:us/state:vt/sldl:orange-2'],
        'OWA': ['ocd-division/country:us/state:vt/sldl:orange-washington-addison'],
        'R-1': ['ocd-division/country:us/state:vt/sldl:rutland-1'],
        'R-2': ['ocd-division/country:us/state:vt/sldl:rutland-2'],
        'R-3': ['ocd-division/country:us/state:vt/sldl:rutland-3'],
        'R-4': ['ocd-division/country:us/state:vt/sldl:rutland-4'],
        'R-6': ['ocd-division/country:us/state:vt/sldl:rutland-6'],
        'R-B': ['ocd-division/country:us/state:vt/sldl:rutland-bennington'],
        'R-W': ['ocd-division/country:us/state:vt/sldl:rutland-windsor-1'],
        'R51': ['ocd-division/country:us/state:vt/sldl:rutland-5-1'],
        'R52': ['ocd-division/country:us/state:vt/sldl:rutland-5-2'],
        'R53': ['ocd-division/country:us/state:vt/sldl:rutland-5-3'],
        'R54': ['ocd-division/country:us/state:vt/sldl:rutland-5-4'],
        'RW2': ['ocd-division/country:us/state:vt/sldl:rutland-windsor-2'],
        'W-1': ['ocd-division/country:us/state:vt/sldl:windham-1'],
        'W-3': ['ocd-division/country:us/state:vt/sldl:windham-3'],
        'W-4': ['ocd-division/country:us/state:vt/sldl:windham-4'],
        'W-5': ['ocd-division/country:us/state:vt/sldl:windham-5'],
        'W-6': ['ocd-division/country:us/state:vt/sldl:windham-6'],
        'W21': ['ocd-division/country:us/state:vt/sldl:windham-2-1'],
        'W22': ['ocd-division/country:us/state:vt/sldl:windham-2-2'],
        'W23': ['ocd-division/country:us/state:vt/sldl:windham-2-3'],
        'WA1': ['ocd-division/country:us/state:vt/sldl:washington-1'],
        'WA2': ['ocd-division/country:us/state:vt/sldl:washington-2'],
        'WA3': ['ocd-division/country:us/state:vt/sldl:washington-3'],
        'WA4': ['ocd-division/country:us/state:vt/sldl:washington-4'],
        'WA5': ['ocd-division/country:us/state:vt/sldl:washington-5'],
        'WA6': ['ocd-division/country:us/state:vt/sldl:washington-6'],
        'WA7': ['ocd-division/country:us/state:vt/sldl:washington-7'],
        'WAC': ['ocd-division/country:us/state:vt/sldl:washington-chittenden'],
        'WBW': ['ocd-division/country:us/state:vt/sldl:windham-bennington-windsor'],
        'WIB': ['ocd-division/country:us/state:vt/sldl:windham-bennington'],
        'Y-1': ['ocd-division/country:us/state:vt/sldl:windsor-1'],
        'Y-2': ['ocd-division/country:us/state:vt/sldl:windsor-2'],
        'Y-5': ['ocd-division/country:us/state:vt/sldl:windsor-5'],
        'Y-R': ['ocd-division/country:us/state:vt/sldl:windsor-rutland'],
        'Y31': ['ocd-division/country:us/state:vt/sldl:windsor-3-1'],
        'Y32': ['ocd-division/country:us/state:vt/sldl:windsor-3-2'],
        'Y41': ['ocd-division/country:us/state:vt/sldl:windsor-4-1'],
        'Y42': ['ocd-division/country:us/state:vt/sldl:windsor-4-2'],
        'YO1': ['ocd-division/country:us/state:vt/sldl:windsor-orange-1'],
        'YO2': ['ocd-division/country:us/state:vt/sldl:windsor-orange-2']
    }
}
